# Generated by Django 3.2.23 on 2023-11-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='kategori',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
